{{- if and .Values.externalDatabase.enabled (include "crewmeld.createExternalDbSecret" .) }}
---
# Secret for external database credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crewmeld.fullname" . }}-external-db-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crewmeld.labels" . | nindent 4 }}
type: Opaque
data:
  EXTERNAL_DB_PASSWORD: {{ .Values.externalDatabase.password | b64enc }}
{{- end }}