{{- if and .Values.redis.enabled (not .Values.redis.auth.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crewmeld.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crewmeld.redis.labels" . | nindent 4 }}
type: Opaque
data:
  redis-password: {{ .Values.redis.auth.password | b64enc | quote }}
{{- end }}
