{{- if and .Values.license.enabled (not .Values.license.existingSecret.enabled) .Values.license.content }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "crewmeld.fullname" . }}-license
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "crewmeld.labels" . | nindent 4 }}
type: Opaque
data:
  license.key: {{ .Values.license.content | b64enc | quote }}
{{- end }}
