/** Terms of Service — locale strings (source: zh-CN) */

export const termsZhCN = {
  title: '服务条款',
  lastUpdated: '最后更新日期：2026 年 4 月 17 日',

  section1Title: '一、服务协议的接受',
  section1Text:
    '欢迎使用 CrewMeld 平台（以下简称"本平台"）。在注册或使用本平台提供的任何服务之前，请您仔细阅读本服务条款。一旦您注册、登录或以其他方式使用本平台服务，即表示您已充分阅读、理解并同意接受本服务条款的全部内容。',

  section2Title: '二、服务内容',
  section2Text:
    '本平台为企业用户提供数字员工管理、智能工作流编排、AI 模型集成等服务。本平台有权根据业务发展需要，对服务内容进行调整、升级或变更，并将通过平台公告或其他合理方式通知用户。',

  section3Title: '三、用户账户',
  section3Item1: '您在注册时应提供真实、准确、完整的信息，并在信息变更时及时更新。',
  section3Item2: '您应妥善保管账户信息和密码，因账户信息泄露所导致的任何损失由您自行承担。',
  section3Item3: '每个账户仅供注册用户本人使用，不得转让、借用或共享。',

  section4Title: '四、用户行为规范',
  section4Text: '您在使用本平台服务时，应遵守适用的法律法规，不得利用本平台从事以下行为：',
  section4Item1: '发布、传播违法违规信息或侵犯他人合法权益的内容；',
  section4Item2: '未经授权访问、篡改本平台系统或数据；',
  section4Item3: '干扰或破坏本平台的正常运行；',
  section4Item4: '利用本平台进行任何可能损害第三方利益的活动。',

  section5Title: '五、知识产权',
  section5Text:
    '本平台的所有内容，包括但不限于文字、图片、软件、界面设计、技术架构等，均受适用知识产权法律保护。未经本平台书面许可，任何人不得复制、修改、传播或以其他方式使用上述内容。',

  section6Title: '六、免责声明',
  section6Item1: '因不可抗力、系统维护升级等原因导致服务中断或数据丢失，本平台不承担责任。',
  section6Item2:
    '本平台集成的第三方 AI 模型生成的内容仅供参考，不构成任何专业建议，由此产生的后果由用户自行承担。',
  section6Item3:
    '本平台不对用户因使用或无法使用服务所产生的任何间接、附带、特殊或惩罚性损害承担责任。',
  section6Item4: '本平台按"现状"和"可用"基础提供服务，不作任何明示或暗示的保证。',

  section7Title: '七、服务变更与终止',
  section7Text:
    '本平台有权在提前通知的情况下修改、暂停或终止部分或全部服务。若用户违反本服务条款，本平台有权立即终止向该用户提供服务，并保留追究法律责任的权利。',

  section8Title: '八、条款修改',
  section8Text:
    '本平台保留随时修改本服务条款的权利。修改后的条款将在平台上公布，您继续使用本平台服务即视为同意修改后的条款。',

  section9Title: '九、适用法律与争议解决',
  section9Text:
    '本服务条款的订立、履行、解释及争议解决均适用本平台运营方注册地所在司法管辖区的法律。因本服务条款引起的或与之相关的争议，双方应首先协商解决；协商不成的，任何一方均有权向运营方所在地有管辖权的法院或仲裁机构提起诉讼或仲裁。',

  section10Title: '十、联系方式',
  section10Text: '如您对本服务条款有任何疑问或建议，请发送邮件至',
  section10Suffix: '与我们联系。',
} as const

export const termsEn: Record<keyof typeof termsZhCN, string> = {
  title: 'Terms of Service',
  lastUpdated: 'Last updated: April 17, 2026',

  section1Title: '1. Acceptance of Terms',
  section1Text:
    'Welcome to the CrewMeld platform ("the Platform"). By registering for, accessing, or using any services provided by the Platform, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service in their entirety.',

  section2Title: '2. Services',
  section2Text:
    'The Platform provides enterprise users with digital workforce management, intelligent workflow orchestration, and AI model integration services. We reserve the right to modify, upgrade, or discontinue any part of the services as business needs evolve, and will notify users through platform announcements or other reasonable means.',

  section3Title: '3. User Accounts',
  section3Item1:
    'You must provide truthful, accurate, and complete information during registration and update it promptly when changes occur.',
  section3Item2:
    'You are responsible for safeguarding your account credentials. Any loss resulting from unauthorised access to your account is your responsibility.',
  section3Item3:
    'Each account is for the sole use of the registered user and may not be transferred, lent, or shared.',

  section4Title: '4. Acceptable Use',
  section4Text:
    'When using the Platform, you must comply with all applicable laws and regulations. You may not use the Platform to:',
  section4Item1:
    'Publish or distribute content that is unlawful or infringes upon the rights of others;',
  section4Item2:
    "Access, tamper with, or compromise the Platform's systems or data without authorisation;",
  section4Item3: 'Interfere with or disrupt the normal operation of the Platform;',
  section4Item4: 'Engage in any activity that may harm third-party interests.',

  section5Title: '5. Intellectual Property',
  section5Text:
    'All content on the Platform — including but not limited to text, images, software, interface design, and technical architecture — is protected by applicable intellectual property laws. No person may copy, modify, distribute, or otherwise use such content without written permission from the Platform.',

  section6Title: '6. Disclaimer of Warranties',
  section6Item1:
    'The Platform shall not be liable for service interruptions or data loss caused by force majeure, system maintenance, or upgrades.',
  section6Item2:
    'Content generated by third-party AI models integrated into the Platform is for reference only and does not constitute professional advice. Users assume all responsibility for reliance on such content.',
  section6Item3:
    'The Platform shall not be liable for any indirect, incidental, special, or punitive damages arising from the use of, or inability to use, the services.',
  section6Item4:
    'The services are provided on an "as is" and "as available" basis, without warranties of any kind, either express or implied.',

  section7Title: '7. Modification and Termination',
  section7Text:
    'We reserve the right to modify, suspend, or terminate any or all services with prior notice. If you violate these Terms of Service, we may immediately terminate your access and reserve the right to pursue legal remedies.',

  section8Title: '8. Changes to Terms',
  section8Text:
    'We reserve the right to amend these Terms of Service at any time. Updated terms will be published on the Platform. Your continued use of the Platform constitutes acceptance of the revised terms.',

  section9Title: '9. Governing Law & Dispute Resolution',
  section9Text:
    "These Terms of Service shall be governed by and construed in accordance with the laws of the jurisdiction in which the Platform operator is incorporated. Any dispute arising out of or in connection with these terms shall first be resolved through good-faith negotiation. If negotiation fails, either party may submit the dispute to the competent courts or arbitration body in the operator's jurisdiction.",

  section10Title: '10. Contact Us',
  section10Text:
    'If you have any questions or suggestions regarding these Terms of Service, please contact us at',
  section10Suffix: '.',
}
